apiVersion: v1
kind: Service
metadata:
  name: ocr-api-service
  namespace: default
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: ocr-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
  type: LoadBalancer
